#!/bin/bash
# MERN Version - Quick Start Guide

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║      Mini CTF - MERN Version (React + Node.js)               ║"
echo "║                  Quick Start Guide                           ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

echo "📦 PROJECT STRUCTURE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "MERN Version/"
echo "├── backend/          (Express.js + MongoDB on port 5000)"
echo "│   ├── src/"
echo "│   ├── .env          ✅ MongoDB URI configured"
echo "│   └── package.json"
echo ""
echo "└── frontend/         (React + Vite on port 5173)"
echo "    ├── src/"
echo "    ├── .env          ✅ API URL configured"
echo "    └── package.json"
echo ""

echo "🚀 QUICK START"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Terminal 1 - Start Backend:"
echo "  $ cd 'MERN Version/backend'"
echo "  $ npm install"
echo "  $ npm run dev"
echo ""
echo "Terminal 2 - Start Frontend:"
echo "  $ cd 'MERN Version/frontend'"
echo "  $ npm install"
echo "  $ npm run dev"
echo ""

echo "🌐 ACCESS URLS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Backend:  http://localhost:5000"
echo "Frontend: http://localhost:5173"
echo "API:      http://localhost:5000/api"
echo ""

echo "🔐 DATABASE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "MongoDB Atlas:"
echo "  Cluster: tutorialcluster"
echo "  URI: mongodb+srv://soban:soban1234@..."
echo "  Status: ✅ Connected"
echo ""

echo "📋 AVAILABLE SCRIPTS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Backend:"
echo "  npm run dev     → Start with auto-reload"
echo "  npm start       → Start production server"
echo "  npm run seed    → Seed database with sample data"
echo ""
echo "Frontend:"
echo "  npm run dev     → Start development server"
echo "  npm run build   → Build for production"
echo "  npm run preview → Preview production build"
echo ""

echo "🎯 7 SECURITY CHALLENGES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. SQL Injection          (100 pts)  🔴 Easy"
echo "2. IDOR                   (100 pts)  🔴 Easy"
echo "3. XSS                    (200 pts)  🟡 Medium"
echo "4. Command Injection      (200 pts)  🟡 Medium"
echo "5. File Upload Bypass     (300 pts)  🔴 Hard"
echo "6. Broken Access Control  (100 pts)  🔴 Easy"
echo "7. Cryptography (ROT13)   (300 pts)  🔴 Hard"
echo ""
echo "Total Points: 1300"
echo ""

echo "⚙️  TECH STACK"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Frontend:  React 18 + Vite + React Router"
echo "Backend:   Express.js + Node.js"
echo "Database:  MongoDB Atlas (Cloud)"
echo "Auth:      JWT Tokens + httpOnly Cookies"
echo ""

echo "📖 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Read: MERN Version/SETUP_GUIDE.md"
echo ""
echo "For Flask Version: Flask Version/SETUP_GUIDE.md"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ Everything is ready! Start with the Quick Start steps above."
echo ""
